require 'i18n'
require 'yaml'
require_relative 'lib/app/constants'
require_relative 'config/i18n'
require_relative 'lib/c_codebreaker/version'
require_relative 'lib/app/entities/output'
require_relative 'lib/app/entities/processor'
