# frozen_string_literal: true

require 'i18n'
require 'yaml'
require_relative 'lib/app/constants'
require_relative 'lib/app/i18n_config'
require_relative 'lib/c_codebreaker/version'
require_relative 'lib/app/modules/data_storage'
require_relative 'lib/app/modules/validator'
require_relative 'lib/app/entities/interface'
require_relative 'lib/app/entities/processor'
require_relative 'lib/app/entities/renderer'
require_relative 'lib/app/entities/statistics'
require_relative 'lib/app/entities/game'
require_relative 'lib/app/entities/rules'
